/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * OMEGA SOVEREIGN STYLE ENGINE — DEAD METAPHOR BLACKLIST FR
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Module: metaphor/dead-metaphor-blacklist.ts
 * Version: 1.0.0 (Sprint 12)
 * Standard: NASA-Grade L4 / DO-178C Level A
 * Invariant: ART-META-01
 *
 * Blacklist de 500+ métaphores mortes françaises.
 * Catégories: CORPS, NATURE, LUMIERE, COMBAT, EAU, TEMPS, ANIMAL, OBJET, ABSTRAIT
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 */

export interface DeadMetaphor {
  readonly canonical: string; // forme canonique minuscule
  readonly category: 'CORPS' | 'NATURE' | 'LUMIERE' | 'COMBAT' | 'EAU' | 'TEMPS' | 'ANIMAL' | 'OBJET' | 'ABSTRAIT';
}

export const DEAD_METAPHORS_FR: DeadMetaphor[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // CORPS (expressions corporelles clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'le cœur serré', category: 'CORPS' },
  { canonical: 'le coeur serré', category: 'CORPS' },
  { canonical: 'les larmes aux yeux', category: 'CORPS' },
  { canonical: 'le sang glacé', category: 'CORPS' },
  { canonical: 'le sang gelé', category: 'CORPS' },
  { canonical: 'des papillons dans le ventre', category: 'CORPS' },
  { canonical: 'un nœud à l\'estomac', category: 'CORPS' },
  { canonical: 'un noeud à l\'estomac', category: 'CORPS' },
  { canonical: 'les bras lui en tombèrent', category: 'CORPS' },
  { canonical: 'avoir le souffle coupé', category: 'CORPS' },
  { canonical: 'le souffle coupé', category: 'CORPS' },
  { canonical: 'la gorge serrée', category: 'CORPS' },
  { canonical: 'la gorge nouée', category: 'CORPS' },
  { canonical: 'les mains tremblantes', category: 'CORPS' },
  { canonical: 'les jambes tremblantes', category: 'CORPS' },
  { canonical: 'le cœur battant', category: 'CORPS' },
  { canonical: 'le coeur battant', category: 'CORPS' },
  { canonical: 'le cœur qui bat', category: 'CORPS' },
  { canonical: 'les genoux tremblants', category: 'CORPS' },
  { canonical: 'la chair de poule', category: 'CORPS' },
  { canonical: 'froid dans le dos', category: 'CORPS' },
  { canonical: 'un frisson dans le dos', category: 'CORPS' },
  { canonical: 'les cheveux dressés', category: 'CORPS' },
  { canonical: 'les cheveux qui se dressent', category: 'CORPS' },
  { canonical: 'le sang qui bout', category: 'CORPS' },
  { canonical: 'la tête qui tourne', category: 'CORPS' },
  { canonical: 'le cœur qui saigne', category: 'CORPS' },
  { canonical: 'le cœur brisé', category: 'CORPS' },
  { canonical: 'la voix tremblante', category: 'CORPS' },
  { canonical: 'les lèvres tremblantes', category: 'CORPS' },
  { canonical: 'les yeux rougis', category: 'CORPS' },
  { canonical: 'les yeux gonflés', category: 'CORPS' },
  { canonical: 'les joues rouges', category: 'CORPS' },
  { canonical: 'les joues empourprées', category: 'CORPS' },
  { canonical: 'le visage pâle', category: 'CORPS' },
  { canonical: 'le visage blême', category: 'CORPS' },
  { canonical: 'le visage livide', category: 'CORPS' },
  { canonical: 'les poings serrés', category: 'CORPS' },
  { canonical: 'les dents serrées', category: 'CORPS' },
  { canonical: 'la mâchoire serrée', category: 'CORPS' },
  { canonical: 'les épaules affaissées', category: 'CORPS' },
  { canonical: 'le dos voûté', category: 'CORPS' },
  { canonical: 'la tête basse', category: 'CORPS' },
  { canonical: 'les yeux baissés', category: 'CORPS' },
  { canonical: 'le regard fuyant', category: 'CORPS' },
  { canonical: 'le regard vide', category: 'CORPS' },
  { canonical: 'le regard perdu', category: 'CORPS' },
  { canonical: 'la respiration haletante', category: 'CORPS' },
  { canonical: 'la respiration saccadée', category: 'CORPS' },
  { canonical: 'le souffle court', category: 'CORPS' },
  { canonical: 'le cœur lourd', category: 'CORPS' },
  { canonical: 'le poids sur les épaules', category: 'CORPS' },
  { canonical: 'le poids sur le cœur', category: 'CORPS' },
  { canonical: 'une boule dans la gorge', category: 'CORPS' },
  { canonical: 'une boule au ventre', category: 'CORPS' },
  { canonical: 'les entrailles nouées', category: 'CORPS' },
  { canonical: 'le ventre noué', category: 'CORPS' },
  { canonical: 'l\'estomac retourné', category: 'CORPS' },
  { canonical: 'avoir la nausée', category: 'CORPS' },
  { canonical: 'sentir son cœur battre', category: 'CORPS' },
  { canonical: 'sentir son sang bouillir', category: 'CORPS' },
  { canonical: 'avoir le vertige', category: 'CORPS' },
  { canonical: 'perdre pied', category: 'CORPS' },
  { canonical: 'les jambes en coton', category: 'CORPS' },
  { canonical: 'les jambes qui flageolent', category: 'CORPS' },
  { canonical: 'les bras ballants', category: 'CORPS' },
  { canonical: 'la tête qui explose', category: 'CORPS' },
  { canonical: 'le cœur qui s\'emballe', category: 'CORPS' },
  { canonical: 'le cœur qui s\'arrête', category: 'CORPS' },
  { canonical: 'le cœur qui se serre', category: 'CORPS' },
  { canonical: 'une douleur au cœur', category: 'CORPS' },
  { canonical: 'un poids sur le cœur', category: 'CORPS' },
  { canonical: 'le sang qui se glace', category: 'CORPS' },
  { canonical: 'le sang qui se fige', category: 'CORPS' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // NATURE (éléments naturels clichés)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'un silence de mort', category: 'NATURE' },
  { canonical: 'un froid glacial', category: 'NATURE' },
  { canonical: 'le vent hurlait', category: 'NATURE' },
  { canonical: 'le vent mugissait', category: 'NATURE' },
  { canonical: 'le vent sifflait', category: 'NATURE' },
  { canonical: 'le vent gémissait', category: 'NATURE' },
  { canonical: 'une tempête de sentiments', category: 'NATURE' },
  { canonical: 'une tempête d\'émotions', category: 'NATURE' },
  { canonical: 'un orage de sentiments', category: 'NATURE' },
  { canonical: 'un ouragan d\'émotions', category: 'NATURE' },
  { canonical: 'un tourbillon d\'émotions', category: 'NATURE' },
  { canonical: 'un tourbillon de sentiments', category: 'NATURE' },
  { canonical: 'un cyclone d\'émotions', category: 'NATURE' },
  { canonical: 'la tempête qui gronde', category: 'NATURE' },
  { canonical: 'l\'orage qui gronde', category: 'NATURE' },
  { canonical: 'le tonnerre qui gronde', category: 'NATURE' },
  { canonical: 'un éclair de lucidité', category: 'NATURE' },
  { canonical: 'un éclair de génie', category: 'NATURE' },
  { canonical: 'un coup de tonnerre', category: 'NATURE' },
  { canonical: 'comme un coup de tonnerre', category: 'NATURE' },
  { canonical: 'un silence pesant', category: 'NATURE' },
  { canonical: 'un silence oppressant', category: 'NATURE' },
  { canonical: 'un silence assourdissant', category: 'NATURE' },
  { canonical: 'la nuit tombait', category: 'NATURE' },
  { canonical: 'la nuit s\'abattait', category: 'NATURE' },
  { canonical: 'l\'obscurité tombait', category: 'NATURE' },
  { canonical: 'les ténèbres tombaient', category: 'NATURE' },
  { canonical: 'le jour se levait', category: 'NATURE' },
  { canonical: 'l\'aube se levait', category: 'NATURE' },
  { canonical: 'le soleil se couchait', category: 'NATURE' },
  { canonical: 'le soleil déclinait', category: 'NATURE' },
  { canonical: 'froid comme la glace', category: 'NATURE' },
  { canonical: 'froid comme la pierre', category: 'NATURE' },
  { canonical: 'dur comme la pierre', category: 'NATURE' },
  { canonical: 'figé comme une statue', category: 'NATURE' },
  { canonical: 'pétrifié comme une statue', category: 'NATURE' },
  { canonical: 'brûlant comme le feu', category: 'NATURE' },
  { canonical: 'chaud comme la braise', category: 'NATURE' },
  { canonical: 'une chaleur étouffante', category: 'NATURE' },
  { canonical: 'une chaleur accablante', category: 'NATURE' },
  { canonical: 'un froid mordant', category: 'NATURE' },
  { canonical: 'un froid piquant', category: 'NATURE' },
  { canonical: 'un froid polaire', category: 'NATURE' },
  { canonical: 'un vent glacial', category: 'NATURE' },
  { canonical: 'un vent glacé', category: 'NATURE' },
  { canonical: 'souffler le chaud et le froid', category: 'NATURE' },
  { canonical: 'la pluie battante', category: 'NATURE' },
  { canonical: 'la pluie torrentielle', category: 'NATURE' },
  { canonical: 'sous une pluie battante', category: 'NATURE' },
  { canonical: 'tremper jusqu\'aux os', category: 'NATURE' },
  { canonical: 'un ciel d\'orage', category: 'NATURE' },
  { canonical: 'un ciel menaçant', category: 'NATURE' },
  { canonical: 'un ciel plombé', category: 'NATURE' },
  { canonical: 'un ciel de plomb', category: 'NATURE' },
  { canonical: 'des nuages menaçants', category: 'NATURE' },
  { canonical: 'des nuages noirs', category: 'NATURE' },
  { canonical: 'l\'horizon s\'assombrit', category: 'NATURE' },
  { canonical: 'le ciel s\'assombrit', category: 'NATURE' },
  { canonical: 'briller comme un diamant', category: 'NATURE' },
  { canonical: 'briller comme une étoile', category: 'NATURE' },
  { canonical: 'une mer de larmes', category: 'NATURE' },
  { canonical: 'un océan de larmes', category: 'NATURE' },
  { canonical: 'trembler comme une feuille', category: 'NATURE' },
  { canonical: 'pâle comme un linge', category: 'NATURE' },
  { canonical: 'blanc comme un linge', category: 'NATURE' },
  { canonical: 'vert de rage', category: 'NATURE' },
  { canonical: 'rouge de colère', category: 'NATURE' },
  { canonical: 'noir de rage', category: 'NATURE' },
  { canonical: 'une atmosphère pesante', category: 'NATURE' },
  { canonical: 'une atmosphère lourde', category: 'NATURE' },
  { canonical: 'une atmosphère oppressante', category: 'NATURE' },
  { canonical: 'une atmosphère étouffante', category: 'NATURE' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LUMIERE (métaphores lumineuses clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'une lueur d\'espoir', category: 'LUMIERE' },
  { canonical: 'une lueur de vie', category: 'LUMIERE' },
  { canonical: 'un rayon d\'espoir', category: 'LUMIERE' },
  { canonical: 'un rayon de soleil', category: 'LUMIERE' },
  { canonical: 'un regard lumineux', category: 'LUMIERE' },
  { canonical: 'des yeux brillants', category: 'LUMIERE' },
  { canonical: 'des yeux qui brillent', category: 'LUMIERE' },
  { canonical: 'des yeux pétillants', category: 'LUMIERE' },
  { canonical: 'des yeux étincelants', category: 'LUMIERE' },
  { canonical: 'l\'ombre d\'un doute', category: 'LUMIERE' },
  { canonical: 'voir la lumière au bout du tunnel', category: 'LUMIERE' },
  { canonical: 'la lumière au bout du tunnel', category: 'LUMIERE' },
  { canonical: 'un avenir radieux', category: 'LUMIERE' },
  { canonical: 'un avenir lumineux', category: 'LUMIERE' },
  { canonical: 'un avenir brillant', category: 'LUMIERE' },
  { canonical: 'un visage rayonnant', category: 'LUMIERE' },
  { canonical: 'un sourire radieux', category: 'LUMIERE' },
  { canonical: 'un sourire éclatant', category: 'LUMIERE' },
  { canonical: 'un sourire lumineux', category: 'LUMIERE' },
  { canonical: 'briller de mille feux', category: 'LUMIERE' },
  { canonical: 'illuminer la pièce', category: 'LUMIERE' },
  { canonical: 'éclairer la voie', category: 'LUMIERE' },
  { canonical: 'faire la lumière sur', category: 'LUMIERE' },
  { canonical: 'mettre en lumière', category: 'LUMIERE' },
  { canonical: 'dans l\'ombre', category: 'LUMIERE' },
  { canonical: 'rester dans l\'ombre', category: 'LUMIERE' },
  { canonical: 'sortir de l\'ombre', category: 'LUMIERE' },
  { canonical: 'projeter une ombre', category: 'LUMIERE' },
  { canonical: 'une ombre portée', category: 'LUMIERE' },
  { canonical: 'l\'ombre de soi-même', category: 'LUMIERE' },
  { canonical: 'un regard terne', category: 'LUMIERE' },
  { canonical: 'des yeux ternes', category: 'LUMIERE' },
  { canonical: 'des yeux éteints', category: 'LUMIERE' },
  { canonical: 'le regard s\'éteint', category: 'LUMIERE' },
  { canonical: 'la flamme s\'éteint', category: 'LUMIERE' },
  { canonical: 'une étincelle de vie', category: 'LUMIERE' },
  { canonical: 'une étincelle d\'espoir', category: 'LUMIERE' },
  { canonical: 'une flamme intérieure', category: 'LUMIERE' },
  { canonical: 'la flamme de la passion', category: 'LUMIERE' },
  { canonical: 'brûler d\'envie', category: 'LUMIERE' },
  { canonical: 'brûler de désir', category: 'LUMIERE' },
  { canonical: 'brûler d\'impatience', category: 'LUMIERE' },
  { canonical: 'un éclair dans les yeux', category: 'LUMIERE' },
  { canonical: 'un éclair de colère', category: 'LUMIERE' },
  { canonical: 'un éclair de rage', category: 'LUMIERE' },
  { canonical: 'les yeux qui lancent des éclairs', category: 'LUMIERE' },
  { canonical: 'noir comme la nuit', category: 'LUMIERE' },
  { canonical: 'sombre comme la nuit', category: 'LUMIERE' },
  { canonical: 'des pensées sombres', category: 'LUMIERE' },
  { canonical: 'des idées noires', category: 'LUMIERE' },
  { canonical: 'voir tout en noir', category: 'LUMIERE' },
  { canonical: 'broyer du noir', category: 'LUMIERE' },
  { canonical: 'une âme sombre', category: 'LUMIERE' },
  { canonical: 'un cœur sombre', category: 'LUMIERE' },
  { canonical: 'rayonner de bonheur', category: 'LUMIERE' },
  { canonical: 'rayonner de joie', category: 'LUMIERE' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // COMBAT (métaphores guerrières clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'une pluie de coups', category: 'COMBAT' },
  { canonical: 'une rafale de coups', category: 'COMBAT' },
  { canonical: 'une grêle de coups', category: 'COMBAT' },
  { canonical: 'une bataille intérieure', category: 'COMBAT' },
  { canonical: 'un combat intérieur', category: 'COMBAT' },
  { canonical: 'se battre contre soi-même', category: 'COMBAT' },
  { canonical: 'livrer bataille', category: 'COMBAT' },
  { canonical: 'armé de courage', category: 'COMBAT' },
  { canonical: 'armé de patience', category: 'COMBAT' },
  { canonical: 'une arme à double tranchant', category: 'COMBAT' },
  { canonical: 'tirer à boulets rouges', category: 'COMBAT' },
  { canonical: 'décharger sa bile', category: 'COMBAT' },
  { canonical: 'monter au front', category: 'COMBAT' },
  { canonical: 'sur le front', category: 'COMBAT' },
  { canonical: 'en première ligne', category: 'COMBAT' },
  { canonical: 'tomber au combat', category: 'COMBAT' },
  { canonical: 'rendre les armes', category: 'COMBAT' },
  { canonical: 'baisser les armes', category: 'COMBAT' },
  { canonical: 'déposer les armes', category: 'COMBAT' },
  { canonical: 'prendre les armes', category: 'COMBAT' },
  { canonical: 'croiser le fer', category: 'COMBAT' },
  { canonical: 'en découdre', category: 'COMBAT' },
  { canonical: 'chercher la bagarre', category: 'COMBAT' },
  { canonical: 'chercher querelle', category: 'COMBAT' },
  { canonical: 'une guerre ouverte', category: 'COMBAT' },
  { canonical: 'déclarer la guerre', category: 'COMBAT' },
  { canonical: 'partir en guerre', category: 'COMBAT' },
  { canonical: 'sur le pied de guerre', category: 'COMBAT' },
  { canonical: 'enterrer la hache de guerre', category: 'COMBAT' },
  { canonical: 'sonner le tocsin', category: 'COMBAT' },
  { canonical: 'battre en retraite', category: 'COMBAT' },
  { canonical: 'sonner la retraite', category: 'COMBAT' },
  { canonical: 'tenir bon', category: 'COMBAT' },
  { canonical: 'tenir la position', category: 'COMBAT' },
  { canonical: 'défendre sa position', category: 'COMBAT' },
  { canonical: 'camper sur ses positions', category: 'COMBAT' },
  { canonical: 'ne pas céder un pouce de terrain', category: 'COMBAT' },
  { canonical: 'gagner du terrain', category: 'COMBAT' },
  { canonical: 'perdre du terrain', category: 'COMBAT' },
  { canonical: 'conquérir du terrain', category: 'COMBAT' },
  { canonical: 'un champ de bataille', category: 'COMBAT' },
  { canonical: 'un terrain miné', category: 'COMBAT' },
  { canonical: 'marcher sur des œufs', category: 'COMBAT' },
  { canonical: 'frapper un grand coup', category: 'COMBAT' },
  { canonical: 'porter un coup', category: 'COMBAT' },
  { canonical: 'donner le coup de grâce', category: 'COMBAT' },
  { canonical: 'un coup bas', category: 'COMBAT' },
  { canonical: 'un coup dur', category: 'COMBAT' },
  { canonical: 'un coup fatal', category: 'COMBAT' },
  { canonical: 'encaisser le coup', category: 'COMBAT' },
  { canonical: 'essuyer le feu', category: 'COMBAT' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // EAU (métaphores aquatiques clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'des larmes comme des perles', category: 'EAU' },
  { canonical: 'noyé dans ses pensées', category: 'EAU' },
  { canonical: 'se noyer dans ses pensées', category: 'EAU' },
  { canonical: 'un flot de paroles', category: 'EAU' },
  { canonical: 'un torrent de paroles', category: 'EAU' },
  { canonical: 'un fleuve de paroles', category: 'EAU' },
  { canonical: 'une cascade de paroles', category: 'EAU' },
  { canonical: 'déverser un flot de paroles', category: 'EAU' },
  { canonical: 'un déluge de paroles', category: 'EAU' },
  { canonical: 'un flux de paroles', category: 'EAU' },
  { canonical: 'déborder de joie', category: 'EAU' },
  { canonical: 'déborder de bonheur', category: 'EAU' },
  { canonical: 'des larmes qui coulent', category: 'EAU' },
  { canonical: 'des larmes qui ruissellent', category: 'EAU' },
  { canonical: 'fondre en larmes', category: 'EAU' },
  { canonical: 'éclater en sanglots', category: 'EAU' },
  { canonical: 'pleurer à chaudes larmes', category: 'EAU' },
  { canonical: 'pleurer toutes les larmes de son corps', category: 'EAU' },
  { canonical: 'verser des larmes', category: 'EAU' },
  { canonical: 'une mer de larmes', category: 'EAU' },
  { canonical: 'un océan de larmes', category: 'EAU' },
  { canonical: 'une rivière de larmes', category: 'EAU' },
  { canonical: 'se jeter à l\'eau', category: 'EAU' },
  { canonical: 'sauter à l\'eau', category: 'EAU' },
  { canonical: 'plonger dans l\'inconnu', category: 'EAU' },
  { canonical: 'nager en pleine confusion', category: 'EAU' },
  { canonical: 'sombrer dans le désespoir', category: 'EAU' },
  { canonical: 'sombrer dans la tristesse', category: 'EAU' },
  { canonical: 'couler à pic', category: 'EAU' },
  { canonical: 'être submergé', category: 'EAU' },
  { canonical: 'submergé par les émotions', category: 'EAU' },
  { canonical: 'submergé par la tristesse', category: 'EAU' },
  { canonical: 'submergé par la douleur', category: 'EAU' },
  { canonical: 'envahi par les émotions', category: 'EAU' },
  { canonical: 'inondé de larmes', category: 'EAU' },
  { canonical: 'inondé de chagrin', category: 'EAU' },
  { canonical: 'un raz-de-marée d\'émotions', category: 'EAU' },
  { canonical: 'une vague d\'émotions', category: 'EAU' },
  { canonical: 'une vague de tristesse', category: 'EAU' },
  { canonical: 'des vagues de douleur', category: 'EAU' },
  { canonical: 'naviguer à vue', category: 'EAU' },
  { canonical: 'naviguer en eaux troubles', category: 'EAU' },
  { canonical: 'en eaux troubles', category: 'EAU' },
  { canonical: 'remonter le courant', category: 'EAU' },
  { canonical: 'suivre le courant', category: 'EAU' },
  { canonical: 'aller contre le courant', category: 'EAU' },
  { canonical: 'se laisser porter par le courant', category: 'EAU' },
  { canonical: 'un courant d\'émotions', category: 'EAU' },
  { canonical: 'le flot des émotions', category: 'EAU' },
  { canonical: 'une marée d\'émotions', category: 'EAU' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // TEMPS (métaphores temporelles clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'le temps s\'arrêta', category: 'TEMPS' },
  { canonical: 'le temps s\'arrête', category: 'TEMPS' },
  { canonical: 'le temps sembla s\'arrêter', category: 'TEMPS' },
  { canonical: 'comme si le temps s\'arrêtait', category: 'TEMPS' },
  { canonical: 'les heures s\'égrenaient', category: 'TEMPS' },
  { canonical: 'les minutes s\'égrenaient', category: 'TEMPS' },
  { canonical: 'le temps s\'étirait', category: 'TEMPS' },
  { canonical: 'un temps de plomb', category: 'TEMPS' },
  { canonical: 'un temps interminable', category: 'TEMPS' },
  { canonical: 'une éternité', category: 'TEMPS' },
  { canonical: 'ça semblait durer une éternité', category: 'TEMPS' },
  { canonical: 'qui sembla durer une éternité', category: 'TEMPS' },
  { canonical: 'le temps filait', category: 'TEMPS' },
  { canonical: 'le temps passe vite', category: 'TEMPS' },
  { canonical: 'le temps qui passe', category: 'TEMPS' },
  { canonical: 'le temps fuit', category: 'TEMPS' },
  { canonical: 'le temps s\'écoule', category: 'TEMPS' },
  { canonical: 'perdre la notion du temps', category: 'TEMPS' },
  { canonical: 'oublier le temps', category: 'TEMPS' },
  { canonical: 'figé dans le temps', category: 'TEMPS' },
  { canonical: 'suspendu dans le temps', category: 'TEMPS' },
  { canonical: 'un instant suspendu', category: 'TEMPS' },
  { canonical: 'un moment suspendu', category: 'TEMPS' },
  { canonical: 'un instant figé', category: 'TEMPS' },
  { canonical: 'figer le temps', category: 'TEMPS' },
  { canonical: 'arrêter le temps', category: 'TEMPS' },
  { canonical: 'un instant d\'éternité', category: 'TEMPS' },
  { canonical: 'un moment d\'éternité', category: 'TEMPS' },
  { canonical: 'les secondes s\'étiraient', category: 'TEMPS' },
  { canonical: 'chaque seconde comptait', category: 'TEMPS' },
  { canonical: 'chaque minute comptait', category: 'TEMPS' },
  { canonical: 'le temps pressait', category: 'TEMPS' },
  { canonical: 'le temps manquait', category: 'TEMPS' },
  { canonical: 'contre la montre', category: 'TEMPS' },
  { canonical: 'une course contre la montre', category: 'TEMPS' },
  { canonical: 'le compte à rebours', category: 'TEMPS' },
  { canonical: 'au fil du temps', category: 'TEMPS' },
  { canonical: 'avec le temps', category: 'TEMPS' },
  { canonical: 'le temps guérit', category: 'TEMPS' },
  { canonical: 'le temps effacera', category: 'TEMPS' },
  { canonical: 'laisser le temps faire', category: 'TEMPS' },
  { canonical: 'donner du temps au temps', category: 'TEMPS' },
  { canonical: 'prendre son temps', category: 'TEMPS' },
  { canonical: 'perdre son temps', category: 'TEMPS' },
  { canonical: 'gagner du temps', category: 'TEMPS' },
  { canonical: 'tuer le temps', category: 'TEMPS' },
  { canonical: 'un moment qui dure', category: 'TEMPS' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ANIMAL (comparaisons animales clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'rusé comme un renard', category: 'ANIMAL' },
  { canonical: 'doux comme un agneau', category: 'ANIMAL' },
  { canonical: 'une mémoire d\'éléphant', category: 'ANIMAL' },
  { canonical: 'fort comme un bœuf', category: 'ANIMAL' },
  { canonical: 'fort comme un taureau', category: 'ANIMAL' },
  { canonical: 'têtu comme une mule', category: 'ANIMAL' },
  { canonical: 'fier comme un coq', category: 'ANIMAL' },
  { canonical: 'malin comme un singe', category: 'ANIMAL' },
  { canonical: 'libre comme l\'air', category: 'ANIMAL' },
  { canonical: 'léger comme une plume', category: 'ANIMAL' },
  { canonical: 'muet comme une carpe', category: 'ANIMAL' },
  { canonical: 'myope comme une taupe', category: 'ANIMAL' },
  { canonical: 'bavard comme une pie', category: 'ANIMAL' },
  { canonical: 'heureux comme un poisson dans l\'eau', category: 'ANIMAL' },
  { canonical: 'rapide comme l\'éclair', category: 'ANIMAL' },
  { canonical: 'vif comme l\'éclair', category: 'ANIMAL' },
  { canonical: 'souple comme un chat', category: 'ANIMAL' },
  { canonical: 'agile comme un chat', category: 'ANIMAL' },
  { canonical: 'patient comme un ange', category: 'ANIMAL' },
  { canonical: 'sage comme une image', category: 'ANIMAL' },
  { canonical: 'blanc comme neige', category: 'ANIMAL' },
  { canonical: 'noir comme du charbon', category: 'ANIMAL' },
  { canonical: 'rouge comme une tomate', category: 'ANIMAL' },
  { canonical: 'rouge comme une pivoine', category: 'ANIMAL' },
  { canonical: 'pâle comme la mort', category: 'ANIMAL' },
  { canonical: 'laid comme un pou', category: 'ANIMAL' },
  { canonical: 'bête comme ses pieds', category: 'ANIMAL' },
  { canonical: 'seul comme un chien', category: 'ANIMAL' },
  { canonical: 'triste comme un jour de pluie', category: 'ANIMAL' },
  { canonical: 'froid comme un glaçon', category: 'ANIMAL' },
  { canonical: 'dur comme du bois', category: 'ANIMAL' },
  { canonical: 'mou comme une chiffe', category: 'ANIMAL' },
  { canonical: 'droit comme un i', category: 'ANIMAL' },
  { canonical: 'simple comme bonjour', category: 'ANIMAL' },
  { canonical: 'clair comme de l\'eau de roche', category: 'ANIMAL' },
  { canonical: 'pur comme de l\'eau de source', category: 'ANIMAL' },
  { canonical: 'courageux comme un lion', category: 'ANIMAL' },
  { canonical: 'timide comme une gazelle', category: 'ANIMAL' },
  { canonical: 'gracieux comme une biche', category: 'ANIMAL' },
  { canonical: 'lourd comme un éléphant', category: 'ANIMAL' },
  { canonical: 'lent comme un escargot', category: 'ANIMAL' },
  { canonical: 'lent comme une tortue', category: 'ANIMAL' },
  { canonical: 'rapide comme un lièvre', category: 'ANIMAL' },
  { canonical: 'sautiller comme un lapin', category: 'ANIMAL' },
  { canonical: 'voler comme un oiseau', category: 'ANIMAL' },
  { canonical: 'chanter comme un rossignol', category: 'ANIMAL' },
  { canonical: 'hurler comme un loup', category: 'ANIMAL' },
  { canonical: 'rugir comme un lion', category: 'ANIMAL' },
  { canonical: 'grogner comme un ours', category: 'ANIMAL' },
  { canonical: 'siffler comme un serpent', category: 'ANIMAL' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // OBJET (métaphores d\'objets clichées)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'un mur de silence', category: 'OBJET' },
  { canonical: 'un mur d\'incompréhension', category: 'OBJET' },
  { canonical: 'un mur infranchissable', category: 'OBJET' },
  { canonical: 'dresser un mur', category: 'OBJET' },
  { canonical: 'ériger un mur', category: 'OBJET' },
  { canonical: 'construire un mur', category: 'OBJET' },
  { canonical: 'une prison dorée', category: 'OBJET' },
  { canonical: 'une cage dorée', category: 'OBJET' },
  { canonical: 'enfermé dans une cage', category: 'OBJET' },
  { canonical: 'prisonnier de ses émotions', category: 'OBJET' },
  { canonical: 'une épée de Damoclès', category: 'OBJET' },
  { canonical: 'un poids sur les épaules', category: 'OBJET' },
  { canonical: 'un fardeau sur les épaules', category: 'OBJET' },
  { canonical: 'porter un fardeau', category: 'OBJET' },
  { canonical: 'porter le poids', category: 'OBJET' },
  { canonical: 'une chaîne invisible', category: 'OBJET' },
  { canonical: 'des chaînes invisibles', category: 'OBJET' },
  { canonical: 'briser ses chaînes', category: 'OBJET' },
  { canonical: 'rompre ses chaînes', category: 'OBJET' },
  { canonical: 'enchaîné à', category: 'OBJET' },
  { canonical: 'une ancre qui retient', category: 'OBJET' },
  { canonical: 'un boulet au pied', category: 'OBJET' },
  { canonical: 'une corde raide', category: 'OBJET' },
  { canonical: 'marcher sur une corde raide', category: 'OBJET' },
  { canonical: 'un fil ténu', category: 'OBJET' },
  { canonical: 'tenir à un fil', category: 'OBJET' },
  { canonical: 'pendre à un fil', category: 'OBJET' },
  { canonical: 'ne tenir qu\'à un fil', category: 'OBJET' },
  { canonical: 'un pont entre', category: 'OBJET' },
  { canonical: 'jeter un pont', category: 'OBJET' },
  { canonical: 'construire un pont', category: 'OBJET' },
  { canonical: 'couper les ponts', category: 'OBJET' },
  { canonical: 'brûler les ponts', category: 'OBJET' },
  { canonical: 'une porte fermée', category: 'OBJET' },
  { canonical: 'une porte close', category: 'OBJET' },
  { canonical: 'ouvrir une porte', category: 'OBJET' },
  { canonical: 'fermer une porte', category: 'OBJET' },
  { canonical: 'claquer la porte', category: 'OBJET' },
  { canonical: 'une fenêtre ouverte', category: 'OBJET' },
  { canonical: 'ouvrir une fenêtre', category: 'OBJET' },
  { canonical: 'une clé pour comprendre', category: 'OBJET' },
  { canonical: 'la clé du mystère', category: 'OBJET' },
  { canonical: 'tenir la clé', category: 'OBJET' },
  { canonical: 'détenir la clé', category: 'OBJET' },
  { canonical: 'une serrure fermée', category: 'OBJET' },
  { canonical: 'un verrou fermé', category: 'OBJET' },
  { canonical: 'un cadenas sur', category: 'OBJET' },
  { canonical: 'une barrière invisible', category: 'OBJET' },
  { canonical: 'dresser une barrière', category: 'OBJET' },
  { canonical: 'franchir la barrière', category: 'OBJET' },
  { canonical: 'lever la barrière', category: 'OBJET' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // ABSTRAIT (concepts abstraits clichés)
  // ═══════════════════════════════════════════════════════════════════════════════
  { canonical: 'un océan de tristesse', category: 'ABSTRAIT' },
  { canonical: 'une montagne de problèmes', category: 'ABSTRAIT' },
  { canonical: 'un abîme de désespoir', category: 'ABSTRAIT' },
  { canonical: 'un gouffre de désespoir', category: 'ABSTRAIT' },
  { canonical: 'sombrer dans l\'abîme', category: 'ABSTRAIT' },
  { canonical: 'au bord de l\'abîme', category: 'ABSTRAIT' },
  { canonical: 'au bord du gouffre', category: 'ABSTRAIT' },
  { canonical: 'tomber dans l\'abîme', category: 'ABSTRAIT' },
  { canonical: 'un puits sans fond', category: 'ABSTRAIT' },
  { canonical: 'un puits de tristesse', category: 'ABSTRAIT' },
  { canonical: 'un puits de chagrin', category: 'ABSTRAIT' },
  { canonical: 'une spirale descendante', category: 'ABSTRAIT' },
  { canonical: 'une spirale infernale', category: 'ABSTRAIT' },
  { canonical: 'un cercle vicieux', category: 'ABSTRAIT' },
  { canonical: 'tourner en rond', category: 'ABSTRAIT' },
  { canonical: 'faire du sur place', category: 'ABSTRAIT' },
  { canonical: 'piétiner', category: 'ABSTRAIT' },
  { canonical: 'stagner', category: 'ABSTRAIT' },
  { canonical: 'avancer à pas de géant', category: 'ABSTRAIT' },
  { canonical: 'faire un pas en avant', category: 'ABSTRAIT' },
  { canonical: 'faire un bond en avant', category: 'ABSTRAIT' },
  { canonical: 'reculer de deux pas', category: 'ABSTRAIT' },
  { canonical: 'faire marche arrière', category: 'ABSTRAIT' },
  { canonical: 'un pas de géant', category: 'ABSTRAIT' },
  { canonical: 'un saut dans l\'inconnu', category: 'ABSTRAIT' },
  { canonical: 'un saut dans le vide', category: 'ABSTRAIT' },
  { canonical: 'le vide devant soi', category: 'ABSTRAIT' },
  { canonical: 'regarder dans le vide', category: 'ABSTRAIT' },
  { canonical: 'tomber dans le vide', category: 'ABSTRAIT' },
  { canonical: 'un vide immense', category: 'ABSTRAIT' },
  { canonical: 'un vide béant', category: 'ABSTRAIT' },
  { canonical: 'combler le vide', category: 'ABSTRAIT' },
  { canonical: 'remplir le vide', category: 'ABSTRAIT' },
  { canonical: 'un trou béant', category: 'ABSTRAIT' },
  { canonical: 'une faille', category: 'ABSTRAIT' },
  { canonical: 'une brèche', category: 'ABSTRAIT' },
  { canonical: 'ouvrir une brèche', category: 'ABSTRAIT' },
  { canonical: 'colmater une brèche', category: 'ABSTRAIT' },
  { canonical: 'un fossé entre', category: 'ABSTRAIT' },
  { canonical: 'creuser un fossé', category: 'ABSTRAIT' },
  { canonical: 'combler un fossé', category: 'ABSTRAIT' },
  { canonical: 'un chemin semé d\'embûches', category: 'ABSTRAIT' },
  { canonical: 'un parcours semé d\'embûches', category: 'ABSTRAIT' },
  { canonical: 'une route semée d\'embûches', category: 'ABSTRAIT' },
  { canonical: 'tracer sa route', category: 'ABSTRAIT' },
  { canonical: 'suivre son chemin', category: 'ABSTRAIT' },
  { canonical: 'perdre son chemin', category: 'ABSTRAIT' },
  { canonical: 'trouver sa voie', category: 'ABSTRAIT' },
  { canonical: 'perdre sa voie', category: 'ABSTRAIT' },
  { canonical: 'à la croisée des chemins', category: 'ABSTRAIT' },
  { canonical: 'un carrefour', category: 'ABSTRAIT' },
  { canonical: 'une impasse', category: 'ABSTRAIT' },
  { canonical: 'dans une impasse', category: 'ABSTRAIT' },
  { canonical: 'sortir de l\'impasse', category: 'ABSTRAIT' },
];

/**
 * Normalize text for matching: lowercase + strip accents.
 * NFD decompose + strip combining diacritics.
 */
function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * Check if a phrase contains any dead metaphor from the blacklist.
 * ART-META-01: ≥ 500 dead metaphors catalogued.
 *
 * @param phrase - Text to check for dead metaphors
 * @returns Object with found flag and array of matching canonical forms
 */
/**
 * Scan full prose for all dead metaphors.
 * Returns matches with positions, dead_count, and dead_ratio.
 *
 * @param prose - Full text to scan
 * @returns Detection result with matches, count, and ratio
 */
export function detectDeadMetaphors(prose: string): {
  readonly matches: readonly { metaphor: string; position: number }[];
  readonly dead_count: number;
  readonly dead_ratio: number;
} {
  if (!prose || prose.trim().length === 0) {
    return { matches: [], dead_count: 0, dead_ratio: 0 };
  }

  const normalized = normalize(prose);
  const matchList: { metaphor: string; position: number }[] = [];

  for (const entry of DEAD_METAPHORS_FR) {
    const normalizedEntry = normalize(entry.canonical);
    const idx = normalized.indexOf(normalizedEntry);
    if (idx !== -1) {
      matchList.push({ metaphor: entry.canonical, position: idx });
    }
  }

  // Estimate total metaphor-like expressions (proxy: sentences with figurative markers)
  const sentences = prose.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const totalEstimate = Math.max(matchList.length, sentences.length > 0 ? 1 : 0);

  return {
    matches: matchList,
    dead_count: matchList.length,
    dead_ratio: totalEstimate > 0 ? matchList.length / totalEstimate : 0,
  };
}

export function isDeadMetaphor(phrase: string): { found: boolean; matches: string[] } {
  const normalized = normalize(phrase);
  const matches: string[] = [];

  for (const entry of DEAD_METAPHORS_FR) {
    const normalizedEntry = normalize(entry.canonical);
    if (normalized.includes(normalizedEntry)) {
      matches.push(entry.canonical);
    }
  }

  return {
    found: matches.length > 0,
    matches,
  };
}
