/**
 * @fileoverview Types for the OMEGA Headless Runner.
 */

import type { Clock, IdFactory } from '@omega/orchestrator-core';

/**
 * Runner configuration options.
 */
export interface RunnerConfig {
  /** Seed for deterministic execution */
  readonly seed: string;
  /** Path to the plan file */
  readonly planPath: string;
  /** Output directory for results */
  readonly outputDir: string;
  /** Optional clock for testing */
  readonly clock?: Clock;
  /** Optional ID factory for testing */
  readonly idFactory?: IdFactory;
  /** Verbosity level: 0=quiet, 1=normal, 2=verbose */
  readonly verbosity: 0 | 1 | 2;
  /** Whether to verify determinism with a second run */
  readonly verifyDeterminism: boolean;
  /** Timeout for entire run in milliseconds */
  readonly timeout?: number;
}

/**
 * Result of a headless run.
 */
export interface HeadlessRunResult {
  /** Whether the run succeeded */
  readonly success: boolean;
  /** Run ID */
  readonly runId: string;
  /** Seed used */
  readonly seed: string;
  /** Start time (ISO) */
  readonly startedAt: string;
  /** End time (ISO) */
  readonly completedAt: string;
  /** Duration in milliseconds */
  readonly durationMs: number;
  /** Number of steps executed */
  readonly stepsExecuted: number;
  /** Number of steps that succeeded */
  readonly stepsSucceeded: number;
  /** Number of steps that failed */
  readonly stepsFailed: number;
  /** Error message if failed */
  readonly error?: string;
  /** Determinism verification result (if enabled) */
  readonly determinismVerified?: boolean;
  /** Output file paths */
  readonly outputFiles: OutputFiles;
}

/**
 * Output file paths generated by the runner.
 */
export interface OutputFiles {
  /** Path to the result JSON file */
  readonly result: string;
  /** Path to the log file */
  readonly log: string;
  /** Path to the hash file */
  readonly hash: string;
}

/**
 * CLI argument parsing result.
 */
export interface ParsedArgs {
  /** Command to execute */
  readonly command: 'run' | 'verify' | 'help' | 'version';
  /** Configuration (for run command) */
  readonly config?: Partial<RunnerConfig>;
  /** Plan path (for run/verify commands) */
  readonly planPath?: string;
  /** Paths for verification (for verify command) */
  readonly verifyPaths?: [string, string];
}

/**
 * Log entry for structured logging.
 */
export interface LogEntry {
  /** Timestamp (ISO) */
  readonly timestamp: string;
  /** Log level */
  readonly level: 'debug' | 'info' | 'warn' | 'error';
  /** Message */
  readonly message: string;
  /** Optional context data */
  readonly context?: Record<string, unknown>;
}

/**
 * Plan file format (JSON).
 */
export interface PlanFile {
  /** Plan version */
  readonly version: string;
  /** Plan metadata */
  readonly metadata?: Record<string, unknown>;
  /** Plan steps */
  readonly steps: PlanFileStep[];
  /** Plan hooks */
  readonly hooks?: PlanFileHooks;
}

/**
 * Step in plan file.
 */
export interface PlanFileStep {
  /** Step ID */
  readonly id: string;
  /** Step kind */
  readonly kind: string;
  /** Step input */
  readonly input: unknown;
  /** Step timeout */
  readonly timeout_ms?: number;
  /** Dependencies */
  readonly depends_on?: readonly string[];
}

/**
 * Hooks in plan file.
 */
export interface PlanFileHooks {
  readonly before_run?: readonly string[];
  readonly after_run?: readonly string[];
  readonly before_step?: readonly string[];
  readonly after_step?: readonly string[];
  readonly on_error?: readonly string[];
}

/**
 * Exit codes for the CLI.
 */
export const ExitCode = {
  SUCCESS: 0,
  GENERAL_ERROR: 1,
  PLAN_NOT_FOUND: 2,
  PLAN_INVALID: 3,
  EXECUTION_FAILED: 4,
  DETERMINISM_FAILED: 5,
  TIMEOUT: 6,
  INVALID_ARGS: 7,
} as const;

export type ExitCode = (typeof ExitCode)[keyof typeof ExitCode];
