/**
 * OMEGA Governance — Markdown Reporter
 * Phase F — Generate Markdown CI report
 *
 * INV-F-07: Report is a pure function of gate results (no side effects).
 */

import type { CIResult } from '../types.js';
import type { ReportOutput } from './types.js';
import { buildSummary, buildRecommendations } from './summary.js';

/** Generate Markdown CI report */
export function generateMarkdownReport(result: CIResult): ReportOutput {
  const summary = buildSummary(result);
  const recommendations = buildRecommendations(result);

  const lines: string[] = [
    '# OMEGA CI Report',
    '',
    `**Run ID**: ${result.run_id}`,
    `**Baseline**: ${result.baseline_version}`,
    `**Verdict**: ${result.verdict}`,
    `**Duration**: ${result.duration_ms}ms`,
    `**Started**: ${result.started_at}`,
    `**Completed**: ${result.completed_at}`,
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total Gates | ${summary.total_gates} |`,
    `| Passed | ${summary.passed_gates} |`,
    `| Failed | ${summary.failed_gates} |`,
    `| Skipped | ${summary.skipped_gates} |`,
    '',
    '## Gate Results',
    '',
  ];

  for (const gate of result.gates) {
    const icon = gate.verdict === 'PASS' ? 'PASS' : gate.verdict === 'FAIL' ? 'FAIL' : 'SKIP';
    lines.push(`### ${gate.gate}: ${gate.name} [${icon}]`);
    lines.push('');
    lines.push(`Duration: ${gate.duration_ms}ms`);
    lines.push('');

    if (gate.checks.length > 0) {
      lines.push('| Check | Status | Message |');
      lines.push('|-------|--------|---------|');
      for (const check of gate.checks) {
        lines.push(`| ${check.id} | ${check.status} | ${check.message} |`);
      }
      lines.push('');
    }

    if (gate.details.length > 0) {
      lines.push('Details:');
      for (const detail of gate.details) {
        lines.push(`- ${detail}`);
      }
      lines.push('');
    }
  }

  if (recommendations.length > 0) {
    lines.push('## Recommendations');
    lines.push('');
    for (const rec of recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by @omega/governance Phase F*');

  return {
    format: 'markdown',
    content: lines.join('\n'),
    filename: `ci-report-${result.run_id}.md`,
  };
}
