# ═══════════════════════════════════════════════════════════════════════════════
# OMEGA PHASE B — GRAVEYARD ARCHIVE SCRIPT
# NASA-Grade: Nothing is deleted, everything is archived with proof
# ═══════════════════════════════════════════════════════════════════════════════

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
Set-Location "C:\Users\elric\omega-project"

$timestamp = Get-Date -Format "yyyyMMdd_HHmm"
$graveyardRoot = "nexus\proof\phase_b\_graveyard\$timestamp"

Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  OMEGA PHASE B — GRAVEYARD ARCHIVE" -ForegroundColor Cyan
Write-Host "  Timestamp: $timestamp" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan

# 1) Create graveyard structure
Write-Host "`n[1/5] Creating graveyard structure..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $graveyardRoot | Out-Null
New-Item -ItemType Directory -Force -Path "$graveyardRoot\tools_harness" | Out-Null
New-Item -ItemType Directory -Force -Path "$graveyardRoot\tools_harness_v2" | Out-Null
New-Item -ItemType Directory -Force -Path "$graveyardRoot\phase_b_artifacts" | Out-Null

# 2) Copy tools/harness/ (old TS harness)
Write-Host "[2/5] Archiving tools/harness/..." -ForegroundColor Yellow
if (Test-Path "tools\harness") {
    Copy-Item -Path "tools\harness\*" -Destination "$graveyardRoot\tools_harness\" -Recurse -Force
    Write-Host "  ✓ tools/harness/ archived" -ForegroundColor Green
} else {
    Write-Host "  ⚠ tools/harness/ not found (skip)" -ForegroundColor Yellow
}

# 3) Copy tools/harness_v2/ (MJS harness)
Write-Host "[3/5] Archiving tools/harness_v2/..." -ForegroundColor Yellow
if (Test-Path "tools\harness_v2") {
    Copy-Item -Path "tools\harness_v2\*" -Destination "$graveyardRoot\tools_harness_v2\" -Recurse -Force
    Write-Host "  ✓ tools/harness_v2/ archived" -ForegroundColor Green
} else {
    Write-Host "  ⚠ tools/harness_v2/ not found (skip)" -ForegroundColor Yellow
}

# 4) Copy existing phase_b artifacts (excluding _graveyard)
Write-Host "[4/5] Archiving nexus/proof/phase_b/ artifacts..." -ForegroundColor Yellow
$items = Get-ChildItem "nexus\proof\phase_b" -Exclude "_graveyard" -ErrorAction SilentlyContinue
foreach ($item in $items) {
    Copy-Item -Path $item.FullName -Destination "$graveyardRoot\phase_b_artifacts\" -Recurse -Force
}
Write-Host "  ✓ phase_b artifacts archived" -ForegroundColor Green

# 5) Generate SHA256 manifest
Write-Host "[5/5] Generating MANIFEST.sha256..." -ForegroundColor Yellow
$manifest = @()
$files = Get-ChildItem -Path $graveyardRoot -Recurse -File
foreach ($file in $files) {
    $hash = (Get-FileHash -Algorithm SHA256 -Path $file.FullName).Hash
    $relativePath = $file.FullName.Replace((Resolve-Path $graveyardRoot).Path + "\", "")
    $manifest += "$hash  $relativePath"
}
$manifest | Out-File -FilePath "$graveyardRoot\MANIFEST.sha256" -Encoding UTF8

# 6) Create TOMBSTONE.md
$tombstone = @"
# TOMBSTONE — Phase B Graveyard Archive

## Metadata
| Field | Value |
|-------|-------|
| Archive Date | $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") |
| Timestamp | $timestamp |
| Archived By | OMEGA B-CLEAN Process |

## What Was Invalidated

### tools/harness/ (Old TS Harness)
- **Status**: INVALID
- **Reason**: Syntax errors in run_b1.ts (broken template string line 7), double imports, skeleton-only code that throws on execution
- **Evidence**: tsx execution fails with empty logs

### tools/harness_v2/ (MJS Harness)
- **Status**: STUB ONLY
- **Reason**: Generates placeholder artifacts without real GENESIS FORGE execution
- **Evidence**: Payloads contain only config hashes, no actual analysis

### nexus/proof/phase_b/ artifacts
- **Status**: INVALID
- **Reason**: Generated by broken/stub harnesses
- **Evidence**: Logs show failures, payloads are stubs

## Replacement

These components are replaced by:
- ``tools/harness_official/`` — New TypeScript harness with real GENESIS FORGE integration
- ``docs/phase-b/B123_CONTRACT.md`` — Formal specification of artifacts

## Manifest

See ``MANIFEST.sha256`` for SHA256 hashes of all archived files.

---
*This archive preserves evidence of why the old implementation failed.*
*Nothing is deleted in OMEGA — everything is archived with proof.*
"@
$tombstone | Out-File -FilePath "$graveyardRoot\TOMBSTONE.md" -Encoding UTF8

Write-Host "`n═══════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  GRAVEYARD ARCHIVE COMPLETE" -ForegroundColor Green
Write-Host "  Location: $graveyardRoot" -ForegroundColor Green
Write-Host "  Files: $($files.Count + 2) (including manifest and tombstone)" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Green

# 7) Mark old harnesses as DEPRECATED (don't delete)
Write-Host "`n[DEPRECATION] Marking old harnesses..." -ForegroundColor Yellow

$deprecationNotice = @"
# ⚠️ DEPRECATED — DO NOT USE

This harness has been **deprecated** and archived.

## Reason
See: ``nexus/proof/phase_b/_graveyard/$timestamp/TOMBSTONE.md``

## Replacement
Use: ``tools/harness_official/``

## Archive Location
``nexus/proof/phase_b/_graveyard/$timestamp/``

---
*Archived on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")*
"@

if (Test-Path "tools\harness") {
    $deprecationNotice | Out-File -FilePath "tools\harness\DEPRECATED.md" -Encoding UTF8
    Write-Host "  ✓ tools/harness/DEPRECATED.md created" -ForegroundColor Green
}

if (Test-Path "tools\harness_v2") {
    $deprecationNotice | Out-File -FilePath "tools\harness_v2\DEPRECATED.md" -Encoding UTF8
    Write-Host "  ✓ tools/harness_v2/DEPRECATED.md created" -ForegroundColor Green
}

Write-Host "`n✅ B-CLEAN GRAVEYARD COMPLETE" -ForegroundColor Green
Write-Host "Next: Run B0 (Contracts) + B-API-PROBE" -ForegroundColor Cyan
