/**
 * OMEGA Capsule Verifier
 * Phase M - Full capsule verification pipeline
 */
import { existsSync, readdirSync } from 'fs';
import { join } from 'path';
import type { CapsuleVerifyResult, CapsuleVerifyOptions } from './types';
import { computeZipHash } from './zip-validator';
import { createSecureTempDir, cleanupTempDir, extractCapsule } from './capsule-extractor';
import { replayVerify } from '../replay';

/**
 * Verifies an OMEGA capsule (zip file) without requiring the repo.
 */
export async function verifyCapsule(
  capsulePath: string,
  options: CapsuleVerifyOptions = {}
): Promise<CapsuleVerifyResult> {
  const errors: string[] = [];
  let tempDir: string | null = null;

  // Check capsule exists
  if (!existsSync(capsulePath)) {
    return {
      success: false,
      capsulePath,
      capsuleHash: '',
      zipValid: false,
      zipValidation: { valid: false, entries: [], errors: ['File not found'], hasZipSlip: false, hasDangerousFiles: false },
      extractedPath: null,
      extractionError: 'File not found',
      replayResult: null,
      verdict: 'ERROR',
      errors: ['Capsule file not found'],
    };
  }

  // Compute capsule hash
  const capsuleHash = computeZipHash(capsulePath);

  // Create temp directory
  tempDir = createSecureTempDir();

  try {
    // Extract capsule
    const extractResult = await extractCapsule(capsulePath, tempDir);

    if (!extractResult.success) {
      return {
        success: false,
        capsulePath,
        capsuleHash,
        zipValid: false,
        zipValidation: { valid: false, entries: [], errors: [extractResult.error ?? 'Extraction failed'], hasZipSlip: false, hasDangerousFiles: false },
        extractedPath: null,
        extractionError: extractResult.error,
        replayResult: null,
        verdict: 'ERROR',
        errors: [extractResult.error ?? 'Extraction failed'],
      };
    }

    // Find the run directory (may be nested one level)
    let runDir = tempDir;
    const contents = readdirSync(tempDir);
    if (contents.length === 1) {
      const nested = join(tempDir, contents[0]);
      if (existsSync(join(nested, 'intent.json')) || existsSync(join(nested, 'hashes.txt'))) {
        runDir = nested;
      }
    }

    // Run replay verification
    const replayResult = replayVerify(runDir, { verbose: options.verbose });

    // Determine verdict
    const verdict = replayResult.success ? 'PASS' : 'FAIL';

    if (!replayResult.success) {
      errors.push(...replayResult.errors);
    }

    return {
      success: replayResult.success,
      capsulePath,
      capsuleHash,
      zipValid: true,
      zipValidation: { valid: true, entries: [], errors: [], hasZipSlip: false, hasDangerousFiles: false },
      extractedPath: runDir,
      extractionError: null,
      replayResult,
      verdict,
      errors,
    };

  } finally {
    // Cleanup temp directory unless keepExtracted
    if (!options.keepExtracted && tempDir) {
      cleanupTempDir(tempDir);
    }
  }
}

/**
 * Generates a text report for capsule verification.
 */
export function generateCapsuleReport(result: CapsuleVerifyResult): string {
  const lines: string[] = [];

  lines.push('# OMEGA Capsule Verification Report');
  lines.push('');
  lines.push(`Capsule: ${result.capsulePath}`);
  lines.push(`Hash: ${result.capsuleHash}`);
  lines.push('');
  lines.push(`## Verdict: ${result.verdict}`);
  lines.push('');

  if (result.zipValid) {
    lines.push('Zip Structure: VALID');
  } else {
    lines.push('Zip Structure: INVALID');
    for (const error of result.zipValidation.errors) {
      lines.push(`  - ${error}`);
    }
  }
  lines.push('');

  if (result.replayResult) {
    lines.push('Replay Verification:');
    lines.push(`  Structure: ${result.replayResult.structureValid ? 'PASS' : 'FAIL'}`);
    lines.push(`  Hashes: ${result.replayResult.hashesValid ? 'PASS' : 'FAIL'}`);
    lines.push(`  Files Checked: ${result.replayResult.filesChecked}`);
    lines.push(`  Files Valid: ${result.replayResult.filesValid}`);
  }
  lines.push('');

  if (result.errors.length > 0) {
    lines.push('Errors:');
    for (const error of result.errors) {
      lines.push(`  - ${error}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('Generated by OMEGA Auditpack v1.0.0');

  return lines.join('\n');
}
