/**
 * OMEGA Governance — Baseline Certificate
 * Phase F — Generate certification for baselines
 */

import { createHash } from 'node:crypto';
import type { BaselineEntry, BaselineManifest } from './types.js';

export interface BaselineCertificate {
  readonly version: string;
  readonly manifest_hash: string;
  readonly intent_count: number;
  readonly intents: readonly string[];
  readonly certified: boolean;
  readonly signature: string;
}

/** Generate a certificate for a baseline */
export function generateBaselineCertificate(
  entry: BaselineEntry,
  _manifest: BaselineManifest,
): BaselineCertificate {
  const certData = {
    version: entry.version,
    manifest_hash: entry.manifest_hash,
    intent_count: entry.intents.length,
    intents: entry.intents,
    certified: entry.certified,
  };

  const signature = createHash('sha256')
    .update(JSON.stringify(certData), 'utf-8')
    .digest('hex');

  return { ...certData, signature };
}

/** Generate Markdown certificate */
export function baselineCertificateToMarkdown(cert: BaselineCertificate): string {
  const lines = [
    '# OMEGA Baseline Certificate',
    '',
    `**Version**: ${cert.version}`,
    `**Certified**: ${cert.certified ? 'YES' : 'NO'}`,
    `**Signature**: ${cert.signature}`,
    '',
    '## Intents',
    '',
    ...cert.intents.map((i) => `- ${i}`),
    '',
    '## Hashes',
    '',
    `- Manifest: ${cert.manifest_hash}`,
    '',
    '---',
    '*Generated by @omega/governance Phase F*',
  ];
  return lines.join('\n');
}
