/**
 * OMEGA Replay Report Generator
 * Phase L - Deterministic report output
 */
import type { ReplayResult } from './types';

/**
 * Generates a deterministic text report from replay result.
 * NO timestamps added (uses recorded timestamp only).
 */
export function generateReplayReport(result: ReplayResult): string {
  const lines: string[] = [];

  lines.push('# OMEGA Replay Verification Report');
  lines.push('');
  lines.push(`Run ID: ${result.runId}`);
  lines.push(`Run Path: ${result.runPath}`);
  lines.push(`Recorded Timestamp: ${result.timestamp || 'N/A'}`);
  lines.push('');
  lines.push(`## Result: ${result.success ? 'PASS' : 'FAIL'}`);
  lines.push('');

  // Structure
  lines.push('## Structure Verification');
  lines.push(`Status: ${result.structureValid ? 'PASS' : 'FAIL'}`);
  for (const file of result.requiredFiles) {
    lines.push(`  - ${file.path}: ${file.exists ? 'OK' : 'MISSING'}`);
  }
  lines.push('');

  // Hashes
  lines.push('## Hash Verification');
  lines.push(`Status: ${result.hashesValid ? 'PASS' : 'FAIL'}`);
  lines.push(`Files Checked: ${result.filesChecked}`);
  lines.push(`Files Valid: ${result.filesValid}`);

  const mismatches = result.fileHashes.filter(f => !f.match);
  if (mismatches.length > 0) {
    lines.push('Mismatches:');
    for (const m of mismatches) {
      lines.push(`  - ${m.path}`);
      lines.push(`    Expected: ${m.expectedHash}`);
      lines.push(`    Actual:   ${m.actualHash ?? 'N/A'}`);
    }
  }
  lines.push('');

  // Tamper Detection
  if (result.tamperResults.length > 0) {
    lines.push('## Tamper Detection');
    for (const tamper of result.tamperResults) {
      if (tamper.detected) {
        lines.push(`  WARNING ${tamper.type}: ${tamper.details}`);
        if (tamper.affectedFiles) {
          for (const file of tamper.affectedFiles) {
            lines.push(`      - ${file}`);
          }
        }
      }
    }
    lines.push('');
  }

  // Errors
  if (result.errors.length > 0) {
    lines.push('## Errors');
    for (const error of result.errors) {
      lines.push(`  - ${error}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by OMEGA Replay Engine v1.0.0');

  return lines.join('\n');
}
