/**
 * OMEGA METROLOGY — aggregate-report.ts
 * ----------------------------------------------------------------------------
 * Reads DATASET + PERFILE + CHURN json, emits:
 *   - OMEGA_METROLOGY_BY_PACKAGE.csv     (1 row / package, all static columns + churn)
 *   - OMEGA_TRANSMISSION_MATRIX.csv      (D2 static edges; D3 latency cols DEFERRED)
 *   - OMEGA_METROLOGY_DASHBOARD.md       (human synthesis: extremes + 10 key numbers)
 * Run: npx tsx scripts/metrology/aggregate-report.ts
 * Scope per Architect directive 2026-05-31: STATIC ONLY (D1,D2,D6,D7,D8).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { REPO_ROOT } from './lib-metrology.ts';

const DIR = path.join(REPO_ROOT, 'docs', 'audit', 'metrology');
const ds = JSON.parse(fs.readFileSync(path.join(DIR, 'OMEGA_METROLOGY_DATASET.json'), 'utf8'));
const churn = JSON.parse(fs.readFileSync(path.join(DIR, 'OMEGA_METROLOGY_CHURN.json'), 'utf8'));

const churnByPkg = new Map<string, any>();
for (const p of churn.byPackage) churnByPkg.set(p.pkg, p);

// ---------- BY_PACKAGE.csv ----------
const cols = [
  'package', 'files_src', 'files_test', 'files_json', 'files_md',
  'bytes_src', 'loc_total', 'loc_code', 'loc_comment', 'loc_blank',
  'chars_total', 'maxLineLen',
  'functions', 'classes', 'interfaces', 'typeAliases', 'enums', 'exports', 'imports',
  'fnLoc_mean', 'fnLoc_p95', 'fnLoc_max',
  'cyclo_mean', 'cyclo_p95', 'cyclo_max', 'nesting_max',
  'asAny', 'asUnknown', 'anyKeyword', 'nonNull', 'tsIgnore', 'tsExpectError', 'eslintDisable',
  'fanIn', 'fanOut', 'instability',
  'dupLines', 'testToCodeRatio',
  'git_commits', 'git_avgAgeDays', 'git_filesStale90d',
];
const rows = ds.packages.map((p: any) => {
  const c = churnByPkg.get(p.pkg) || {};
  return [
    p.pkg, p.files_src, p.files_test, p.files_json, p.files_md,
    p.bytes_src, p.loc_total, p.loc_code, p.loc_comment, p.loc_blank,
    p.chars_total, p.maxLineLen,
    p.functions, p.classes, p.interfaces, p.typeAliases, p.enums, p.exports, p.imports,
    r(p.fnLoc.mean), p.fnLoc.p95, p.fnLoc.max,
    r(p.fnCyclo.mean), p.fnCyclo.p95, p.fnCyclo.max, p.fnNesting.max,
    p.asAny, p.asUnknown, p.anyKeyword, p.nonNull, p.tsIgnore, p.tsExpectError, p.eslintDisable,
    p.fanIn, p.fanOut, p.instability,
    p.dupLines, p.testToCodeRatio,
    c.commits ?? '', c.avgAgeDays ?? '', c.filesStale90d ?? '',
  ].join(',');
});
fs.writeFileSync(path.join(DIR, 'OMEGA_METROLOGY_BY_PACKAGE.csv'),
  [cols.join(','), ...rows].join('\n') + '\n', 'utf8');

// ---------- TRANSMISSION_MATRIX.csv (D2 static; D3 runtime DEFERRED) ----------
const tCols = ['source', 'target', 'importSites', 'importedSymbols',
  'payloadBytes_DEFERRED', 'latency_p50_ns_DEFERRED', 'latency_p95_ns_DEFERRED', 'callsPerSec_DEFERRED'];
const tRows = ds.repo.graph.edgeList.map((e: any) =>
  [e.source, e.target, e.importSites, e.importedSymbols, '', '', '', ''].join(','));
fs.writeFileSync(path.join(DIR, 'OMEGA_TRANSMISSION_MATRIX.csv'),
  [tCols.join(','), ...tRows].join('\n') + '\n', 'utf8');

// ---------- DASHBOARD.md ----------
const R = ds.repo;
const fmt = (n: number) => n.toLocaleString('en-US');
const ex = ds.extremes;
const md = `# OMEGA — METROLOGY DASHBOARD (static)

> Generated by \`scripts/metrology/aggregate-report.ts\` · stamp \`${ds.meta.stamp}\`
> Scope: \`packages/\` + \`src/\` + \`gateway/\` (excl node_modules/dist/.git/coverage)
> Method: TypeScript compiler **parser-only** AST + git log. Lane = **STATIC ONLY** (D1/D2/D6/D7/D8) per Architect directive 2026-05-31. D3 runtime / D9 prose / D10 resources **DEFERRED** until Phase 1 PASS.

## 10 chiffres-clés OMEGA

| # | Métrique | Valeur |
|---|----------|--------|
| 1 | Fichiers TS analysés (src + test) | **${fmt(R.files.ts_src)} + ${fmt(R.files.ts_test)} = ${fmt(R.files.ts_src + R.files.ts_test)}** |
| 2 | LOC code (hors comment/blank) | **${fmt(R.loc.code)}** |
| 3 | Fonctions | **${fmt(R.declarations.functions)}** |
| 4 | Interfaces / types / classes / enums | ${fmt(R.declarations.interfaces)} / ${fmt(R.declarations.typeAliases)} / ${fmt(R.declarations.classes)} / ${fmt(R.declarations.enums)} |
| 5 | Complexité cyclomatique (médiane / p95 / max) | ${R.functionDist.cyclomatic.median} / ${R.functionDist.cyclomatic.p95} / **${R.functionDist.cyclomatic.max}** |
| 6 | Graphe packages : nœuds / arêtes / cycles | ${R.graph.nodes} / ${R.graph.edges} / **${R.graph.cycleCount}** |
| 7 | Profondeur max DAG | ${R.graph.maxDagDepth} |
| 8 | Casts \`as any\`+\`as unknown\` / \`any\` keyword / non-null \`!\` | ${R.typing.asAny}+${R.typing.asUnknown} / ${R.typing.anyKeyword} / ${R.typing.nonNull} |
| 9 | Duplication (window=${R.duplication.windowSize}) | **${R.duplication.dupRatioPct}%** (${R.duplication.interPkgGroups} groupes inter-pkg) |
| 10 | Ratio commentaires / code | ${R.loc.commentRatio} |

## Extrêmes (top 1 par axe)

| Axe | Fichier | Valeur |
|-----|---------|--------|
| Plus gros fichier (octets) | \`${ex.largestFilesByBytes[0].rel}\` | ${fmt(ex.largestFilesByBytes[0].bytes)} o |
| Plus de LOC | \`${ex.largestFilesByLoc[0].rel}\` | ${fmt(ex.largestFilesByLoc[0].loc)} lignes |
| Fonction la plus complexe | \`${ex.mostComplexFiles[0].rel}\` | cyclo ${ex.mostComplexFiles[0].maxCyclo} |
| Imbrication la plus profonde | \`${ex.deepestNesting[0].rel}\` | nesting ${ex.deepestNesting[0].maxNest} |
| Ligne la plus longue | \`${ex.longestLines[0].rel}\` | ${fmt(ex.longestLines[0].maxLineLen)} chars |
| Plus gros clone (occurrences) | \`${R.duplication.biggestClone.locs[0]}\` | ×${R.duplication.biggestClone.size} |
| Hot-spot #1 (churn×cyclo) | \`${churn.topHotspots[0].rel}\` | ${fmt(churn.topHotspots[0].hotspot)} (${churn.topHotspots[0].commits} commits × ${churn.topHotspots[0].sumCyclo} cyclo) |

## Graphe — hubs & SPOF

**Top fan-in (Ca — dépendants):**
${R.graph.topFanIn.slice(0, 6).map((x: any) => `- \`${x.pkg}\` ← ${x.fanIn}`).join('\n')}

**Top fan-out (Ce — dépendances):**
${R.graph.topFanOut.slice(0, 6).map((x: any) => `- \`${x.pkg}\` → ${x.fanOut}`).join('\n')}

**Orphelins (fan-in = fan-out = 0, candidats archéologie):** ${R.graph.orphans.length}
${R.graph.orphans.map((p: string) => `\`${p}\``).join(', ')}

## Top 8 packages par LOC code

| Package | LOC code | Fns | Cyclo max | fanIn | fanOut | I | dup lines | commits |
|---------|---------:|----:|----------:|------:|-------:|--:|----------:|--------:|
${ds.packages.slice(0, 8).map((p: any) => {
  const c = churnByPkg.get(p.pkg) || {};
  return `| ${p.pkg} | ${fmt(p.loc_code)} | ${fmt(p.functions)} | ${p.fnCyclo.max} | ${p.fanIn} | ${p.fanOut} | ${p.instability} | ${fmt(p.dupLines)} | ${c.commits ?? '–'} |`;
}).join('\n')}

## Top 8 hot-spots (zones à risque = churn × complexité)

| Fichier | commits | Σcyclo | hotspot |
|---------|--------:|-------:|--------:|
${churn.topHotspots.slice(0, 8).map((h: any) => `| \`${h.rel}\` | ${h.commits} | ${h.sumCyclo} | ${fmt(h.hotspot)} |`).join('\n')}

---
*Datasets: \`OMEGA_METROLOGY_DATASET.json\`, \`OMEGA_METROLOGY_CHURN.json\`, \`OMEGA_METROLOGY_PERFILE.json\` · CSV: \`OMEGA_METROLOGY_BY_PACKAGE.csv\`, \`OMEGA_TRANSMISSION_MATRIX.csv\` · Méthode: \`OMEGA_METROLOGY_METHOD.md\`*
`;
fs.writeFileSync(path.join(DIR, 'OMEGA_METROLOGY_DASHBOARD.md'), md, 'utf8');

function r(x: number) { return Math.round(x * 100) / 100; }
process.stderr.write('[aggregate] wrote BY_PACKAGE.csv, TRANSMISSION_MATRIX.csv, DASHBOARD.md\n');
