/**
 * OMEGA METROLOGY — M0.b BENCH (Option B) — scribe weaveLLM vs sovereign forge
 * ============================================================================
 * DEC-009 gate bench. REAL Ollama qwen3:32b. READ-ONLY engine code (harness only).
 * Decision ref: NCR-M0B-SCRIBE-PRODUCTION-PATH-NO-LLM (Architect GO Option B).
 *
 * Same Golden brief ("Le Gardien") → same GenesisPlan → SAME first scene generated by:
 *   - scribe : weaveLLM (LLM path, NOT runScribe) + scribe Ollama provider (qwen3:32b)
 *   - sovereign: assembleForgePacket(scene) + runSovereignForgeWithPacket + sovereign Ollama provider (qwen3:32b)
 * Both prose outputs scored by the SAME instrument: judgeAestheticV3 (S-Oracle V2),
 * judge temp 0.0. Judge variance probed (LLM judge, same seed-limit as CF4).
 *
 * CF1 scribe=weaveLLM (not runScribe). CF2 two distinct Ollama provider impls.
 * CF3 resolved by Option B (same task: generate-from-plan). CF4 Ollama seed prompt-only.
 * CF5 gen params: {temperature, top_p, max_tokens, num_ctx} equalized; repeat-penalty
 *     asymmetry hardcoded (sovereign 1.4/0.6/256 vs scribe Ollama-default) → documented, NOT forced.
 * CF6 14D contract state measured empirically (logged) — Option B uses assembleForgePacket
 *     (plan-derived 14D), unlike the V2.3-A hollow path; recorded per run.
 *
 * Env: M0B_N (default 5), M0B_MAXTOK (2048), M0B_TEMP (0.8), M0B_MODEL (qwen3:32b),
 *      M0B_JUDGE_VAR_K (3), M0B_SMOKE (=1 → N=1, MAXTOK=320, K=1, fast wiring check).
 * Run (cwd = packages/sovereign-engine for dist/session resolution parity):
 *   npx tsx ../../scripts/metrology/m0b-bench.ts
 */
process.env.OMEGA_CHUNKED_V4 = '1';
process.env.OMEGA_PROMPT_V4 = '1';

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import * as path from 'node:path';

import { createGenesisPlan } from '../../packages/genesis-planner/src/planner.js';
import { createDefaultConfig } from '../../packages/genesis-planner/src/config.js';
import type { GenesisPlan, Scene } from '../../packages/genesis-planner/src/types.js';

// scribe (LLM weaver path)
import { weaveLLM } from '../../packages/scribe-engine/src/weaver-llm.js';
import { segmentPlan } from '../../packages/scribe-engine/src/segmenter.js';
import { buildSkeleton } from '../../packages/scribe-engine/src/skeleton.js';
import { createScribeProvider } from '../../packages/scribe-engine/src/providers/factory.js';
import type { OllamaProviderConfig as ScribeOllamaConfig } from '../../packages/scribe-engine/src/providers/ollama-provider.js';

// sovereign (forge + assembler + judge)
import { assembleForgePacket } from '../../packages/sovereign-engine/src/input/forge-packet-assembler.js';
import { runSovereignForgeWithPacket } from '../../packages/sovereign-engine/src/engine.js';
import { judgeAestheticV3 } from '../../packages/sovereign-engine/src/oracle/aesthetic-oracle.js';
import { createOllamaProvider } from '../../packages/sovereign-engine/src/runtime/ollama-provider.js';
import { DEFAULT_VOICE_GENOME } from '../../packages/sovereign-engine/src/voice/voice-genome.js';
import type {
  ForgePacket, StyleProfile, KillLists, CanonEntry, ForgeContinuity,
} from '../../packages/sovereign-engine/src/types.js';
import type { MacroSScore } from '../../packages/sovereign-engine/src/oracle/macro-score-types.js';

// ---------- config ----------
const SMOKE = !!process.env.M0B_SMOKE;
const N = SMOKE ? 1 : parseInt(process.env.M0B_N ?? '5', 10);
const MAXTOK = parseInt(process.env.M0B_MAXTOK ?? (SMOKE ? '320' : '2048'), 10);
const TEMP = parseFloat(process.env.M0B_TEMP ?? '0.8');
const MODEL = process.env.M0B_MODEL ?? 'qwen3:32b';
const JUDGE_VAR_K = SMOKE ? 1 : parseInt(process.env.M0B_JUDGE_VAR_K ?? '3', 10);
const OLLAMA_URL = process.env.M0B_OLLAMA_URL ?? 'http://localhost:11434';
const GOLDEN = process.env.M0B_GOLDEN ?? 'golden/intents/intent_pack_gardien.json';
const REPO_ROOT = path.resolve(process.cwd(), process.cwd().endsWith('sovereign-engine') ? '../..' : '.');

const TS = '2026-01-01T00:00:00.000Z'; // deterministic timestamp (engines)
const OUT_DIR = path.join(REPO_ROOT, 'docs', 'audit', 'metrology', 'm0b-runs');

function log(s: string) { process.stderr.write(s + '\n'); }
function words(s: string): number { return s.split(/\s+/).filter((w) => w.length > 0).length; }
function stats(xs: number[]) {
  const n = xs.length; if (!n) return { n: 0, mean: 0, stdev: 0, min: 0, max: 0 };
  const mean = xs.reduce((a, b) => a + b, 0) / n;
  const stdev = Math.sqrt(xs.reduce((a, b) => a + (b - mean) ** 2, 0) / n);
  return { n, mean, stdev, min: Math.min(...xs), max: Math.max(...xs) };
}
function axes(ms: MacroSScore) {
  return {
    composite: ms.composite, min_axis: ms.min_axis, verdict: ms.verdict,
    ECC: ms.macro_axes.ecc.score, RCI: ms.macro_axes.rci.score,
    SII: ms.macro_axes.sii.score, IFI: ms.macro_axes.ifi.score, AAI: ms.macro_axes.aai.score,
  };
}

// ---------- providers (CF5: equalize temperature + max_tokens; top_p both 0.92; num_ctx both default) ----------
const scribeProvider = createScribeProvider({
  mode: 'ollama', forceModel: MODEL, ollamaUrl: OLLAMA_URL,
  temperature: TEMP, maxTokens: MAXTOK,
} as ScribeOllamaConfig, 'prose');

const sovProvider = createOllamaProvider({
  baseUrl: OLLAMA_URL, model: MODEL,
  draftTemperature: TEMP, judgeTemperature: 0.0,
  draftMaxTokens: MAXTOK, judgeMaxTokens: 2000,
  // sovereign hardcoded anti-loop defaults kept (CF5 documented, not forced to scribe parity)
});
// dedicated judge provider (temp 0) — used as the SAME instrument for BOTH engines' prose
const judgeProvider = createOllamaProvider({
  baseUrl: OLLAMA_URL, model: MODEL,
  draftTemperature: 0.0, judgeTemperature: 0.0,
  draftMaxTokens: MAXTOK, judgeMaxTokens: 2000,
});

// ---------- build Golden plan + first scene + sovereign packet ----------
function buildContext() {
  const pack = JSON.parse(readFileSync(path.join(REPO_ROOT, GOLDEN), 'utf8'));
  const g = createDefaultConfig();
  const { plan } = createGenesisPlan(pack.intent, pack.canon, pack.constraints, pack.genome, pack.emotion, g, TS);
  const scene0: Scene = plan.arcs[0]!.scenes[0]!;

  // single-scene reduced plan → scribe weaves ONLY scene[0]
  const reducedPlan: GenesisPlan = {
    ...plan,
    arcs: [{ ...plan.arcs[0]!, scenes: [scene0] }],
    scene_count: 1,
    beat_count: scene0.beats.length,
  };

  const style_profile: StyleProfile = {
    version: '1.0.0', universe: 'literary_fiction',
    lexicon: {
      signature_words: ['phare', 'mer', 'lumiere', 'profondeur', 'silence'],
      forbidden_words: pack.constraints.banned_words ?? [],
      abstraction_max_ratio: 0.20, concrete_min_ratio: 0.60,
    },
    rhythm: {
      avg_sentence_length_target: pack.genome?.target_avg_sentence_length ?? 15,
      gini_target: 0.45, max_consecutive_similar: 2, min_syncopes_per_scene: 2, min_compressions_per_scene: 1,
    },
    tone: { dominant_register: 'soutenu', intensity_range: [0.2, 0.9] as readonly [number, number] },
    imagery: {
      recurrent_motifs: ['phare', 'ocean', 'lumiere'],
      density_target_per_100_words: 3, banned_metaphors: pack.constraints.forbidden_cliches ?? [],
    },
    voice: DEFAULT_VOICE_GENOME,
  };
  const kill_lists: KillLists = {
    banned_words: pack.constraints.banned_words ?? [],
    banned_cliches: pack.constraints.forbidden_cliches ?? [],
    banned_ai_patterns: [], banned_filter_words: [],
  };
  const canon: CanonEntry[] = (pack.canon?.entries ?? []).map((e: any) => ({ id: e.id, statement: e.statement }));
  const continuity: ForgeContinuity = { previous_scene_summary: '', character_states: [], open_threads: [] };

  return { pack, plan, reducedPlan, scene0, style_profile, kill_lists, canon, continuity };
}

// ---------- per-engine generation ----------
function genScribe(ctx: ReturnType<typeof buildContext>, runIdx: number): { prose: string; ms: number } {
  const t0 = Date.now();
  const segments = segmentPlan(ctx.reducedPlan);
  const skeleton = buildSkeleton(segments, ctx.reducedPlan);
  const seed = `m0b_scribe_${ctx.scene0.scene_id}_${runIdx}`;
  const doc = weaveLLM(skeleton, ctx.plan, ctx.pack.constraints, ctx.pack.genome, ctx.pack.emotion, scribeProvider, seed, ctx.pack);
  const prose = doc.paragraphs.map((p: any) => p.text).join('\n\n');
  return { prose, ms: Date.now() - t0 };
}

async function genSovereign(packet: ForgePacket): Promise<{ prose: string; internal: MacroSScore; ms: number }> {
  const t0 = Date.now();
  const result = await runSovereignForgeWithPacket(packet, sovProvider);
  return { prose: result.final_prose, internal: result.macro_score, ms: Date.now() - t0 };
}

async function main() {
  log(`=== OMEGA M0.b BENCH (Option B) — ${MODEL} ===`);
  log(`N=${N} MAXTOK=${MAXTOK} TEMP=${TEMP} JUDGE_VAR_K=${JUDGE_VAR_K} SMOKE=${SMOKE}`);
  mkdirSync(OUT_DIR, { recursive: true });

  const ctx = buildContext();
  log(`Golden: ${ctx.pack.intent.title} | plan scenes=${ctx.plan.scene_count} | scene0=${ctx.scene0.scene_id} (${ctx.scene0.beats.length} beats, target=${ctx.scene0.target_word_count}w)`);

  // sovereign packet (assembled from plan+scene0). run_id varied per run for seed (CF4: not passed to API anyway)
  const packet0 = assembleForgePacket({
    plan: ctx.plan, scene: ctx.scene0, style_profile: ctx.style_profile,
    kill_lists: ctx.kill_lists, canon: ctx.canon, continuity: ctx.continuity,
    run_id: 'm0b_probe', language: 'fr',
  });
  // CF6 measurement: is the emotion contract's 14D populated under Option B?
  const q1_14d = (packet0.emotion_contract?.curve_quartiles?.[0] as any)?.target_14d ?? {};
  const cf6 = { target_14d_keys: Object.keys(q1_14d).length, sample: q1_14d };
  log(`CF6 14D state: Q1 target_14d has ${cf6.target_14d_keys} keys`);

  // DRY: validate all non-LLM wiring (genesis/assembler/segmenter/skeleton/types) without any Ollama call
  if (process.env.M0B_DRY) {
    const segments = segmentPlan(ctx.reducedPlan);
    const skeleton = buildSkeleton(segments, ctx.reducedPlan);
    log(`[DRY] packet_id=${packet0.packet_id} scene=${packet0.scene_id} beats=${packet0.beats.length}`);
    log(`[DRY] scribe skeleton: ${skeleton.segment_count} segments, scene_order=${JSON.stringify(skeleton.scene_order)}`);
    log(`[DRY] wiring OK — exiting before Ollama (set M0B_SMOKE=1 for a real 1-run check).`);
    return;
  }

  const runs: any[] = [];
  for (let i = 0; i < N; i++) {
    log(`\n--- run ${i + 1}/${N} ---`);
    const entry: any = { run: i };
    // SOVEREIGN
    try {
      const packet = assembleForgePacket({
        plan: ctx.plan, scene: ctx.scene0, style_profile: ctx.style_profile,
        kill_lists: ctx.kill_lists, canon: ctx.canon, continuity: ctx.continuity,
        run_id: `m0b_sov_${i}`, language: 'fr',
      });
      const sov = await genSovereign(packet);
      const sovJudge = await judgeAestheticV3(packet, sov.prose, judgeProvider, null);
      entry.sovereign = { words: words(sov.prose), gen_ms: sov.ms, ...axes(sovJudge), internal_composite: sov.internal.composite };
      log(`  sovereign: comp=${sovJudge.composite.toFixed(1)} min=${sovJudge.min_axis.toFixed(1)} words=${words(sov.prose)} gen=${(sov.ms / 1000).toFixed(0)}s`);
      if (i === 0) writeFileSync(path.join(OUT_DIR, 'sample_sovereign.txt'), sov.prose, 'utf8');
    } catch (e: any) { entry.sovereign = { error: String(e?.message ?? e).slice(0, 400) }; log(`  sovereign ERROR: ${entry.sovereign.error}`); }
    // SCRIBE
    try {
      const sc = genScribe(ctx, i);
      // judge scribe prose against the SAME packet0 (identical instrument)
      const scJudge = await judgeAestheticV3(packet0, sc.prose, judgeProvider, null);
      entry.scribe = { words: words(sc.prose), gen_ms: sc.ms, ...axes(scJudge) };
      log(`  scribe:    comp=${scJudge.composite.toFixed(1)} min=${scJudge.min_axis.toFixed(1)} words=${words(sc.prose)} gen=${(sc.ms / 1000).toFixed(0)}s`);
      if (i === 0) writeFileSync(path.join(OUT_DIR, 'sample_scribe.txt'), sc.prose, 'utf8');
    } catch (e: any) { entry.scribe = { error: String(e?.message ?? e).slice(0, 400) }; log(`  scribe ERROR: ${entry.scribe.error}`); }
    runs.push(entry);
    writeFileSync(path.join(OUT_DIR, 'm0b_runs.json'), JSON.stringify({ config: { N, MAXTOK, TEMP, MODEL, JUDGE_VAR_K }, cf6, runs }, null, 2), 'utf8');
  }

  // JUDGE VARIANCE PROBE: judge run0's prose K extra times to isolate judge noise
  const judgeVar: any = {};
  const s0 = runs[0];
  if (s0?.sovereign && !s0.sovereign.error) {
    const sovProse = readFileSync(path.join(OUT_DIR, 'sample_sovereign.txt'), 'utf8');
    const comps: number[] = [s0.sovereign.composite];
    for (let k = 1; k < JUDGE_VAR_K; k++) comps.push((await judgeAestheticV3(packet0, sovProse, judgeProvider, null)).composite);
    judgeVar.sovereign = stats(comps);
  }
  if (s0?.scribe && !s0.scribe.error) {
    const scProse = readFileSync(path.join(OUT_DIR, 'sample_scribe.txt'), 'utf8');
    const comps: number[] = [s0.scribe.composite];
    for (let k = 1; k < JUDGE_VAR_K; k++) comps.push((await judgeAestheticV3(packet0, scProse, judgeProvider, null)).composite);
    judgeVar.scribe = stats(comps);
  }

  // AGGREGATE
  const ok = (e: any, eng: string) => e[eng] && !e[eng].error;
  const pick = (eng: string, key: string) => runs.filter((r) => ok(r, eng)).map((r) => r[eng][key]);
  const agg: any = { sovereign: {}, scribe: {} };
  for (const eng of ['sovereign', 'scribe']) {
    for (const key of ['composite', 'min_axis', 'ECC', 'RCI', 'SII', 'IFI', 'AAI', 'words', 'gen_ms']) {
      agg[eng][key] = stats(pick(eng, key));
    }
  }
  const dComposite = (agg.sovereign.composite.mean ?? 0) - (agg.scribe.composite.mean ?? 0);

  const out = { config: { N, MAXTOK, TEMP, MODEL, JUDGE_VAR_K, golden: GOLDEN }, cf6, runs, aggregate: agg, judgeVariance: judgeVar, delta_composite_sov_minus_scribe: dComposite };
  writeFileSync(path.join(OUT_DIR, 'm0b_runs.json'), JSON.stringify(out, null, 2), 'utf8');
  log(`\n=== AGGREGATE ===`);
  log(`sovereign composite: ${agg.sovereign.composite.mean?.toFixed(2)} ± ${agg.sovereign.composite.stdev?.toFixed(2)} (n=${agg.sovereign.composite.n})`);
  log(`scribe    composite: ${agg.scribe.composite.mean?.toFixed(2)} ± ${agg.scribe.composite.stdev?.toFixed(2)} (n=${agg.scribe.composite.n})`);
  log(`Δ composite (sov - scribe): ${dComposite.toFixed(2)}`);
  if (judgeVar.sovereign) log(`judge noise (sov prose): ±${judgeVar.sovereign.stdev?.toFixed(2)} over k=${judgeVar.sovereign.n}`);
  log(`Wrote ${path.join(OUT_DIR, 'm0b_runs.json')}`);
}

main().catch((e) => { log('FATAL: ' + (e?.stack ?? e)); process.exit(1); });
