/**
 * @fileoverview Event type definitions for OMEGA Decision Engine.
 * @module @omega/decision-engine/types/events
 */

import type { BuildVerdict } from './verdicts.js';

/**
 * Type of runtime event.
 */
export type RuntimeEventType = 'VERDICT_OBSERVED';

/**
 * Metadata attached to a runtime event.
 */
export interface RuntimeEventMetadata {
  /** Unix timestamp (ms) when event was observed */
  readonly observedAt: number;
  /** SHA-256 hash for integrity verification */
  readonly hash: string;
}

/**
 * Runtime event generated by SENTINEL when observing a verdict.
 * Immutable record of an observation.
 */
export interface RuntimeEvent {
  /** Unique identifier for this event */
  readonly id: string;
  /** Unix timestamp (ms) when event was created */
  readonly timestamp: number;
  /** Type of event */
  readonly type: RuntimeEventType;
  /** The observed verdict */
  readonly verdict: BuildVerdict;
  /** Event metadata */
  readonly metadata: RuntimeEventMetadata;
}

/**
 * Snapshot of SENTINEL runtime state.
 */
export interface RuntimeSnapshot {
  /** Total events observed */
  readonly totalEvents: number;
  /** Last event ID observed */
  readonly lastEventId: string | null;
  /** Last event timestamp */
  readonly lastEventTimestamp: number | null;
  /** Snapshot timestamp */
  readonly snapshotTimestamp: number;
}

/**
 * Statistics from SENTINEL.
 */
export interface SentinelStats {
  /** Total verdicts observed */
  readonly totalObserved: number;
  /** Count by source */
  readonly bySource: Record<string, number>;
  /** Count by verdict type */
  readonly byVerdict: Record<string, number>;
  /** Average observation latency (ms) */
  readonly avgLatencyMs: number;
  /** Max observation latency (ms) */
  readonly maxLatencyMs: number;
}
